.TH regd "1"
.SH NAME
.PP
regd \- Registry daemon.

.SH SYNOPSIS
.PP
regd <\fICOMMAND\fP> [\fIARGUMENTS\fP]

.SH DESCRIPTION
.PP
Stores information in the form of name/value pairs (tokens)
and returns it in response to commands.

.PP
Token (name and value) is a pair of arbitrary Unicode strings
separated by '=' character. Name string therefore cannot
contain '=' character.

.PP
The value string is retrieved with a command using the name
string as the token identificator.

.PP
Tokens are grouped in sections. Token name can contain an
optional section name, which is the part of the name up to the
first colon. E.g.:
"SECTION NAME : token name".
If the section name is not present in the token name, the token
is stored in the section named 'general'.

.PP
A token can be one of two types regarding its lifetime:
\fIsession\fP token or \fIpersistent\fP token. Session tokens
exist in the registry from the moment of their addition
to the program exit or until their removal with a command.
Persistent tokens are stored in a disk file, automatically
loaded in the registry on each program start and exist until
they are explicitly removed with a removal command.

.PP
From encrypted files secure tokens can be loaded. Secure tokens
are always session tokens (they are never stored on disk).
Also secure tokens are not included in the print output of
listing commands.

.SH COMMANDS
.SS \fB\-\-start\fP
.PP
Start regd. This command can be used with a command line option '\fB\-\-log\-level\fP' (see below).

.SS \-\-stop
.PP
Stop regd.

.SS \-\-restart
.PP
Restart regd.

.SS \-\-check
.PP
Check if the regd is running.

.SS \-\-add <\fIname=value\fP>
.PP
Add a session token. If a token with such name already exists, the token value is not updated.

.SS \-\-set <\fIname=value\fP>
.PP
Add a session token. If a token with such name already exists, the token value is updated.

.SS \-\-add\-pers <\fIname=value\fP>
.PP
Same as \fB\-\-add\fP, but the token is added to the persistent tokens.

.SS \-\-set\-pers <\fIname=value\fP>
.PP
Same as \fB\-\-set\fP, but the token is added to the persistent tokens.

.SS \-\-get <\fIname\fP>
.PP
Get the value of a session token.

.SS \-\-get\-pers <\fIname\fP>
.PP
Get the value of a persistent token.

.SS \-\-get\-sec <\fIname\fP>
.PP
Get the value of a secure token.

.SS \-\-list\-all
.PP
Print all the session tokens and persistent tokens. (Secure tokens are not listed.)

.SS \-\-list\-session [\fIsection1\fP[ \fIsection2\fP...]]
.PP
Print the specified sections of session tokens or all sections if sections are not specified.

.SS \-\-list\-pers [\fIsection1\fP[ \fIsection2\fP...]]
.PP
Print the specified sections of persistent tokens or all sections if sections are not specified.

.SS \-\-load <\fIname1=value1\fP>[\fIname2=value2\fP...]
.PP
Add multiple session tokens. Each name/value pair needs to be separated from the previous one with the token separator. The default token separator is a three\-character sequence: \fI@#$\fP . With the default separator multiple tokens are specified like this:
"name1=value1@#$name2=value2"
The value of the token separator can be customized in \fIregd.conf\fP file.

.SS \-\-load\-pers <\fIname1=value1\fP>[\fIname2=value2\fP...]
.PP
Same as \fB\-\-load\fP, but adds persistent tokens, rather
than session ones.

.SS \-\-load\-file <\fIfilename\fP>
.PP
Add session tokens from the file. \fIfilename\fP \- the path
of the file with tokens.

.SS \-\-load\-file\-pers <\fIfilename\fP>
.PP
Same as \fB\-\-load\-file\fP, but adds persistent tokens, rather
than session ones.

.SS \-\-load\-file\-sec [\fIfilename\fP]
.PP
Add secure tokens from an encrypted file. \fIfilename\fP \- the
path of the file with secure tokens. \fIfilename\fP can be
ommited, in which case the default encrypted file will be
read. The default name of the default file is:
\fI\~/.sec/safestor.gpg\fP
The name of the default encrypted file can be specified in
\fIregd.conf\fP.
The default command for reading encrypted files is:
"gpg \-\-textmode \-d FILENAME"
For this default command could be used, \fIgpg\fP, \fIgpg\-agent\fP
and \fIpinentry\fP programs needs to be installed and run on the
computer. With this command, when the first query during a
program session for getting a value of a secure token
('\-\-get\-sec') is received, a \fIpinentry\fP dialog window is
shown to the user for receiving the password.
If the password is correct, \fIgpg\fP program then reads the
contents of the encrypted file and pipes the file text to
the \fIregd\fP, where it's stored in RAM.
With this procedure decrypted contents are never written to
a disk and always remain in RAM.

.PP
The command for reading encrypted files can be changed and
specified in the \fIregd.conf\fP.

.SH COMMAND LINE START OPTIONS
.SS \-\-log\-level <\fIlog\_level\fP>
.PP
This command line start option sets the level of the log
output. Log level can be one of the following values:
DEBUG, INFO, WARNING, ERROR, CRITICAL.
Log level is the type of events which which cause the
program to produce output.

.SH CONFIGURATION FILE
.PP
The configuration file \fIregd.conf\fP is read on the program
startup. Options in \fIregd.conf\fP residing in \fI/etc/regd/\fP
are system\-wide ( applied for all users using regd ). The
system\-wide options can be overriden with user\-level
\fIregd.conf\fP residing in \fI\~/.config/regd/\fP.

.PP
Options that can be set in \fIregd.conf\fP are described in
\fI/etc/regd/conf.regd\fP file.

.SH AUTHOR
.PP
Albert Berger 
\[la]nbdspcl@gmail.com\[ra]
